### ISSUE TITLE
invalid pg-promise initialization

### ISSUE THREAD

**Issue by vitaly-t** [peter-ungvari/typical-backend#1]
You are missing a step here: https://github.com/peter-ungvari/typical-backend/blob/3a93b90a85a229c9e33d8ce17d63a6beea73bdfb/node-coffee-pgsql-express/dao/personDao.coffee

pgp needs initialization call first, see again - [Getting Started](https://github.com/vitaly-t/pg-promise#getting-started)

**Comment by peter-ungvari** [comment]
Thanks, fixed.
